 CREATE TABLE poll (
    poll_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    question VARCHAR(255) NOT NULL,
    chooseoption1 VARCHAR(255) NOT NULL,
    chooseoption2 VARCHAR(255) NOT NULL,
    chooseoption3 VARCHAR(255) NOT NULL,
    chooseoption4 VARCHAR(255) NOT NULL,
    PRIMARY KEY (poll_id)
);

CREATE TABLE pollchooseoption(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    poll_id INTEGER NOT NULL,
    userName VARCHAR(50) NOT NULL,
    chooseoption VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);